@Restaurant.API_HostAddress = https://localhost:44339



###

GET {{Restaurant.API_HostAddress}}/api/Restaurant



###

GET {{Restaurant.API_HostAddress}}/api/Restaurant/3

###

POST {{Restaurant.API_HostAddress}}/api/Restaurant
Content-Type: application/json
 {
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "56-567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-656"
}


###

DELETE {{Restaurant.API_HostAddress}}/api/Restaurant/5

###
