@Restaurant.API_HostAddress = https://localhost:44339



###

GET {{Restaurant.API_HostAddress}}/api/Restaurant



###

GET {{Restaurant.API_HostAddress}}/api/Restaurant/145

###

POST {{Restaurant.API_HostAddress}}/api/Restaurant
Content-Type: application/json
 {
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "56-567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-656"
}


###

DELETE {{Restaurant.API_HostAddress}}/api/Restaurant/11

###


PATCH {{Restaurant.API_HostAddress}}/api/Restaurant/10
Content-Type: application/json

{
  "name": "Spicy",
  "description": "A culinar like no other",
   "HasDelivery": false
}

###



###

POST {{Restaurant.API_HostAddress}}/api/Restaurant/3/dishes
Content-Type: application/json

{
  "name": "Spaghetti Boloness",
  "description": "classic Pasta like no other",
  "price":30,
  "kiloCalories": 330
}

###
