@Restaurant.API_HostAddress = https://localhost:44339
@token=CfDJ8Aw4hYbhb-hEhAEKdI62n7VdPescDMw_GChz6UjtgdcWkom9S-b8ZvuMo4aIoFuryxO8dcUcrx2cwUuTH5MHvYhKyAd-V4RQHSdwM6U13_bGzf9dbq8NtmoBrcW11134b5ZP1y8VXWz5Z7GYfwXWXO4-Ty3Llqqe_eYO4_mJ-kAXsa4fZpJ2ubEBAY9XSw1EXGAFS4bDqBVPAB6EmqkoNLI9t5teqQd6gTyPFXy_NaTrC8bz-4W5FTsufNF76_F-VLqecGdUAQQhBLXc9H0DFEbg47-bO-uIx15s2sahdnfE7XKdjjr-xDCY-0XFHBDZ2Bf72uIc-IOe7kXKwiO-aqDq14Fly_9nHxHpRNvbQr6DwOuxjbJ3PnbNFI_VT0Bv3pYSVGt_K9eHb8kUly1oSJNW4eWFQFRZkdTmHGzJ2YM-9z4DRn_XcimR6e1l8DdTGpKpbyvf-2xhjenrZf424aaTed7ygqPR_kV3_uGz8-W2PeAgsHVzsiQpg3xdk1KFn4p1VN8RlgZ7Cz2NWqsBO-avAbhuTmxAWE0dvyX1wzJnxcJsjgkauzNCG1yiyShjdtCMZjZW5PbEKnxerIuyOpPgtQiDp7emLggMko4TJC-dwMLsaKFmVwyy1I9TJ5KYak8YpyritdA550Vupkw4ThlV5bb7jeOJmDLE7gKZUIWfO1MhW24fsN_hCvx5LtvJUg


###

GET {{Restaurant.API_HostAddress}}/api/Restaurant



###

GET {{Restaurant.API_HostAddress}}/api/Restaurant/3
Authorization:Bearer {{token}}

###

POST {{Restaurant.API_HostAddress}}/api/Restaurant
Content-Type: application/json
 {
  "Name": "Spicy Delights",
  "Description": "A culinary experience like no other",
  "Category": "Italian",
  "HasDelivery": true,
  "ContactEmail": "info@gourmetdelights.com",
  "ContactNumber": "56-567",
  "City": "Metropolis",
  "Street": "456 Gourmet Avenue",
  "PostalCode": "54-656"
}


###

DELETE {{Restaurant.API_HostAddress}}/api/Restaurant/11

###


PATCH {{Restaurant.API_HostAddress}}/api/Restaurant/10
Content-Type: application/json

{
  "name": "Spicy",
  "description": "A culinar like no other",
   "HasDelivery": false
}

###



###

POST {{Restaurant.API_HostAddress}}/api/Restaurant/3/dishes
Content-Type: application/json

{
  "name": "Spaghetti Boloness",
  "description": "classic Pasta like no other",
  "price":30,
  "kiloCalories": 330
}

###
POST {{Restaurant.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password1!"
}
###
POST {{Restaurant.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
  "email": "testuser@test.com",
  "password": "Password1!"
}
###
